import test from 'node:test'
import assert from 'node:assert/strict'
import {createAgentStatusReadCapability} from '../packages/dingtalk-dsh-assistant/agent-query-status.js'
const r={id:'uat3',kind:'kubernetes',kubeconfig:'D:/trusted/kube.yml',server:'https://127.0.0.1:6443',skipTlsVerify:false,namespace:'uat3',deployment:'dataset'}
const d={metadata:{name:'dataset',namespace:'uat3',uid:'dep',resourceVersion:'1',generation:1},spec:{replicas:1},status:{readyReplicas:1,availableReplicas:1,observedGeneration:1}}
const pod={metadata:{name:'dataset-one',namespace:'uat3',uid:'pod',resourceVersion:'2',ownerReferences:[{kind:'ReplicaSet',uid:'rs',controller:true}]},spec:{containers:[{name:'dataset',image:'registry/dataset:uat3',env:[{name:'PASSWORD',value:'SUPERSECRET'}],ports:[{containerPort:8080}],resources:{limits:{memory:'1Gi'}}}]},status:{phase:'Running',containerStatuses:[{name:'dataset',ready:true,imageID:'registry/dataset@sha256:'+'a'.repeat(64),restartCount:0}]}}
function runner(calls,{drift=false}={}){let reads=0;return async(cmd,args,opts)=>{calls.push({cmd,args,opts});let value;if(args.includes('logs'))return{stdout:'2026-09-28T00:00:00Z ERROR java.lang.IllegalStateException: password=SUPERSECRET request body PRIVATE\n2026-09-28T00:00:01Z at com.hiq.Service.run(Service.java:42)\n'};if(args.includes('deployment')){value=structuredClone(d);if(++reads>1&&drift)value.metadata.resourceVersion='3'}else if(args.includes('replicasets'))value={items:[{metadata:{uid:'rs',ownerReferences:[{kind:'Deployment',name:'dataset',uid:'dep',controller:true}]}}]};else value={items:[pod]};return{stdout:JSON.stringify(value)}}}
test('实际受信平台读取复用，部署/配置/日志字段投影且无原文秘密',async()=>{const calls=[],tool=createAgentStatusReadCapability({resources:[r],execFileImpl:runner(calls)}),input={resourceId:r.id},scope={statusIds:[r.id]};const output=await tool.execute({input,scope});assert.equal(output.values.pods[0].containers[0].imageId,'registry/dataset@sha256:'+'a'.repeat(64));assert.ok(!JSON.stringify(output).includes('SUPERSECRET'));assert.ok(!JSON.stringify(output).includes('PRIVATE'));assert.equal(output.values.pods[0].containers[0].logSummary.diagnostics[1].codeLocation,'com.hiq.Service.run(Service.java:42)');assert.equal((await tool.verify({input,scope,output})).passed,true);assert.ok(calls.every(c=>c.cmd==='kubectl'&&c.opts.timeout===12000));assert.ok(calls.every(c=>!c.args.includes('secret')&&!c.args.includes('exec')));assert.ok(calls.find(c=>c.args.includes('logs')).args.includes('--tail=200'))})
test('授权、目标、版本漂移及执行异常固定拒绝',async()=>{const calls=[],tool=createAgentStatusReadCapability({resources:[r],execFileImpl:runner(calls)});await assert.rejects(tool.execute({input:{resourceId:r.id},scope:{statusIds:[]}}),/QUERY_SCOPE_DENIED/);assert.equal(calls.length,0);assert.throws(()=>createAgentStatusReadCapability({resources:[{...r,namespace:'x;delete'}]}),/QUERY_STATUS_CONFIG_INVALID/);await assert.rejects(createAgentStatusReadCapability({resources:[r],execFileImpl:runner([],{drift:true})}).execute({input:{resourceId:r.id},scope:{statusIds:[r.id]}}),/QUERY_SOURCE_CHANGED/);await assert.rejects(createAgentStatusReadCapability({resources:[r],execFileImpl:async()=>{throw Error('SECRET')}}).execute({input:{resourceId:r.id},scope:{statusIds:[r.id]}}),e=>e.message==='QUERY_RUNTIME_UNAVAILABLE')})
