import test from 'node:test'
import assert from 'node:assert/strict'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { mkdtemp, mkdir, writeFile, readFile, unlink, readdir, symlink } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { tmpdir } from 'node:os'
import { createManagedWorkspaces, assertWorkspaceConflictsResolved } from '../packages/dingtalk-dsh-assistant/execution-workspace.js'
import { freezeCandidate, readCandidate, verifyCandidate } from '../packages/dingtalk-dsh-assistant/execution-candidate.js'
import { createGitDelivery } from '../packages/dingtalk-dsh-assistant/execution-git.js'

const exec = promisify(execFile)
const git = async (directory, ...args) => (await exec('git', ['-C', directory, ...args], { windowsHide: true })).stdout.trim()
async function setup() {
  const directory = await mkdtemp(join(tmpdir(), 'dsh-managed-workspace-')), root = join(directory, 'managed'), sourceRepository = join(directory, 'source')
  await mkdir(root); await mkdir(sourceRepository)
  await git(sourceRepository, 'init', '-b', 'main'); await git(sourceRepository, 'config', 'user.name', 'Synthetic'); await git(sourceRepository, 'config', 'user.email', 'synthetic@example.invalid')
  await writeFile(join(sourceRepository, 'value.txt'), 'base\n'); await writeFile(join(sourceRepository, 'deleted.txt'), 'keep base\n')
  await git(sourceRepository, 'add', '.'); await git(sourceRepository, 'commit', '-m', 'base')
  const baseCommit = await git(sourceRepository, 'rev-parse', 'HEAD'), adapter = await createManagedWorkspaces({ root, sourceRepository })
  const input = { runId: 'run-synthetic', generation: 1, requirementDigest: 'a'.repeat(64), baseCommit }
  return { directory, root, sourceRepository, adapter, input }
}

test('Windows深目录超过MAX_PATH仍能提取固定基线并冻结读取候选', { skip: process.platform !== 'win32' }, async () => {
  const f = await setup(), root = join(f.directory, 'nested-' + 'x'.repeat(Math.max(1, 245 - f.directory.length - 87)))
  await mkdir(root)
  const adapter = await createManagedWorkspaces({ root, sourceRepository: f.sourceRepository })
  const prepared = await adapter.prepare(f.input)
  assert.ok(join(prepared.directory, '.git/objects/pack/pack-' + 'a'.repeat(40) + '.keep').length > 260)
  assert.equal((await adapter.execute(prepared)).status, 'succeeded')
  const candidate = await freezeCandidate({ repository: prepared.directory, baseCommit: f.input.baseCommit, generation: 1, requirementDigest: f.input.requirementDigest })
  assert.equal((await (await readCandidate(candidate)).readFile('value.txt')).toString(), 'base\n')
})
test('受管代际只取固定base，不带源未提交文件；旧代删除与用户变更不污染新代', async () => {
  const f = await setup()
  await writeFile(join(f.sourceRepository, 'value.txt'), 'source user edit\n'); await writeFile(join(f.sourceRepository, 'private.txt'), 'untracked\n')
  const index = await readFile(join(f.sourceRepository, '.git', 'index'))
  const first = await f.adapter.prepare(f.input)
  assert.ok(Object.isFrozen(first)); assert.deepEqual(await readdir(f.root), [])
  assert.equal((await f.adapter.execute(first)).status, 'succeeded')
  await unlink(join(first.directory, 'deleted.txt')); await writeFile(join(first.directory, 'value.txt'), 'old user edit\n'); await writeFile(join(first.directory, 'old.txt'), 'old\n')
  assert.equal((await f.adapter.reconcile(first)).status, 'succeeded')
  assert.equal(await readFile(join(first.directory, 'value.txt'), 'utf8'), 'old user edit\n')
  const second = await f.adapter.prepare({ ...f.input, generation: 2, requirementDigest: 'b'.repeat(64) })
  await f.adapter.execute(second)
  assert.notEqual(second.directory, first.directory)
  assert.equal(await readFile(join(second.directory, 'deleted.txt'), 'utf8'), 'keep base\n')
  assert.equal(await readFile(join(second.directory, 'value.txt'), 'utf8'), 'base\n')
  await assert.rejects(readFile(join(second.directory, 'old.txt')), { code: 'ENOENT' })
  await assert.rejects(readFile(join(second.directory, 'private.txt')), { code: 'ENOENT' })
  assert.deepEqual(await readFile(join(f.sourceRepository, '.git', 'index')), index)
  assert.equal(await git(f.sourceRepository, 'rev-parse', 'HEAD'), f.input.baseCommit)
  assert.equal(await readFile(join(f.sourceRepository, 'value.txt'), 'utf8'), 'source user edit\n')
})
test('同一目录并发只允许一个执行者，重复只能对账；残缺目录不覆盖', async () => {
  const f = await setup(), prepared = await f.adapter.prepare(f.input)
  const results = await Promise.allSettled([f.adapter.execute(prepared), f.adapter.execute(prepared)])
  assert.equal(results.filter(result => result.status === 'fulfilled').length, 1)
  assert.equal(results.find(result => result.status === 'rejected').reason.code, 'EEXIST')
  const next = await f.adapter.prepare({ ...f.input, generation: 2 })
  await mkdir(dirname(next.directory)); await writeFile(join(dirname(next.directory), 'evidence.txt'), 'preserve')
  assert.equal((await f.adapter.reconcile(next)).status, 'unknown')
  await assert.rejects(f.adapter.execute(next), { code: 'EEXIST' })
  assert.equal(await readFile(join(dirname(next.directory), 'evidence.txt'), 'utf8'), 'preserve')
})
test('身份或真实HEAD冲突明确拒绝，不能伪装恢复成功', async () => {
  const f = await setup(), prepared = await f.adapter.prepare(f.input)
  await f.adapter.execute(prepared)
  await writeFile(join(dirname(prepared.directory), 'metadata.json'), '{}')
  await assert.rejects(f.adapter.reconcile(prepared), { code: 'WORKSPACE_IDENTITY_CONFLICT' })
  await writeFile(join(dirname(prepared.directory), 'metadata.json'), JSON.stringify(prepared))
  await git(prepared.directory, '-c', 'user.name=Synthetic', '-c', 'user.email=synthetic@example.invalid', 'commit', '--allow-empty', '-m', 'foreign')
  await assert.rejects(f.adapter.reconcile(prepared), { code: 'WORKSPACE_BASE_CONFLICT' })
})
test('源hook/filter与链接目录不准入；prepare也不会修改源index', async () => {
  const f = await setup(), index = await readFile(join(f.sourceRepository, '.git', 'index'))
  await git(f.sourceRepository, 'config', 'filter.bad.smudge', 'invalid-tool')
  await assert.rejects(f.adapter.prepare(f.input), { code: 'WORKSPACE_UNSUPPORTED_CONFIG' })
  await git(f.sourceRepository, 'config', '--unset', 'filter.bad.smudge')
  await writeFile(join(f.sourceRepository, '.git', 'hooks', 'post-checkout'), 'invalid-tool')
  await assert.rejects(f.adapter.prepare(f.input), { code: 'WORKSPACE_HOOKS_UNSUPPORTED' })
  const linked = join(f.directory, 'linked'); await symlink(f.root, linked, 'junction')
  await assert.rejects(createManagedWorkspaces({ root: linked, sourceRepository: f.sourceRepository }), { code: 'WORKSPACE_LINK_UNSUPPORTED' })
  assert.deepEqual(await readFile(join(f.sourceRepository, '.git', 'index')), index)
})
test('base tree的symlink/gitlink在任何目的写入之前拒绝', async () => {
  const f = await setup()
  await git(f.sourceRepository, 'update-index', '--add', '--cacheinfo', `160000,${f.input.baseCommit},submodule`)
  await git(f.sourceRepository, 'commit', '-m', 'unsupported gitlink')
  const baseCommit = await git(f.sourceRepository, 'rev-parse', 'HEAD')
  await assert.rejects(f.adapter.prepare({ ...f.input, baseCommit }), { code: 'WORKSPACE_ENTRY_UNSUPPORTED' })
  assert.deepEqual(await readdir(f.root), [])
})

test('v13原生合并树保留UAT新增删除，解决文本冲突后双父提交保持被测树', async () => {
  const f=await setup(), initial=f.input.baseCommit
  await writeFile(join(f.sourceRepository,'value.txt'),'development\n')
  await git(f.sourceRepository,'add','.');await git(f.sourceRepository,'commit','-m','development')
  const development=await git(f.sourceRepository,'rev-parse','HEAD')
  await git(f.sourceRepository,'checkout','-b','uat',initial)
  await writeFile(join(f.sourceRepository,'value.txt'),'uat\n');await writeFile(join(f.sourceRepository,'uat-only.txt'),'must preserve\n')
  await unlink(join(f.sourceRepository,'deleted.txt'))
  await git(f.sourceRepository,'add','-A');await git(f.sourceRepository,'commit','-m','uat changes')
  const targetCommit=await git(f.sourceRepository,'rev-parse','HEAD'),sourceIndex=await readFile(join(f.sourceRepository,'.git/index'))
  const adapter=await createManagedWorkspaces({root:f.root,sourceRepository:f.sourceRepository,targetCommit,taskBase:initial})
  const prepared=await adapter.prepare({...f.input,baseCommit:development})
  assert.equal(prepared.version,2);assert.deepEqual(prepared.conflictPaths,['value.txt'])
  await adapter.execute(prepared)
  assert.equal(await git(prepared.directory,'rev-parse','HEAD'),development)
  assert.equal(await git(prepared.directory,'write-tree'),prepared.mergeTree)
  assert.equal(await readFile(join(prepared.directory,'uat-only.txt'),'utf8'),'must preserve\n')
  await assert.rejects(readFile(join(prepared.directory,'deleted.txt')),/ENOENT/)
  await assert.rejects(assertWorkspaceConflictsResolved(prepared),/WORKSPACE_CONFLICT_UNRESOLVED/)
  await writeFile(join(prepared.directory,'value.txt'),'resolved business result\n')
  await assertWorkspaceConflictsResolved(prepared)
  const candidate=await freezeCandidate({repository:prepared.directory,baseCommit:development,generation:1,requirementDigest:f.input.requirementDigest})
  const checks=[{id:'business',version:'1',run:async ({readFile})=>({passed:(await readFile('value.txt')).toString()==='resolved business result\n',log:'验证合并后的候选字节'})}]
  const verification=await verifyCandidate({candidate,checks})
  const remote=join(f.directory,'remote.git');await mkdir(remote);await git(remote,'init','--bare')
  const delivery=await createGitDelivery({repository:prepared.directory,remote,branch:'delivery',author:{name:'Test',email:'test@example.invalid'},mergeParent:targetCommit})
  const commit=await delivery.prepareCommit({candidate,verification,requiredChecks:[{id:'business',version:'1'}],message:'resolved merge',date:'1790150400 +0000'})
  assert.deepEqual(commit.changedPaths,['value.txt']);assert.equal(commit.changeBaseCommit,targetCommit)
  await delivery.executeCommit(commit)
  assert.equal(await git(prepared.directory,'show','-s','--format=%P',commit.commitId),`${development} ${targetCommit}`)
  assert.equal(await git(prepared.directory,'rev-parse',`${commit.commitId}^{tree}`),candidate.tree)
  assert.equal((await git(prepared.directory,'merge-tree','--write-tree',targetCommit,commit.commitId)).split(/\s/)[0],candidate.tree)
  assert.equal(await git(f.sourceRepository,'rev-parse','HEAD'),targetCommit)
  assert.deepEqual(await readFile(join(f.sourceRepository,'.git/index')),sourceIndex)
  assert.equal((await adapter.reconcile(prepared)).status,'succeeded')
})

test('v13拒绝删除重命名和二进制冲突，包括二进制add/add，不生成可交付工作目录',async()=>{
  for(const kind of ['binary-add','binary','delete','rename','rename-add']){
    const binary=kind.startsWith('binary'),f=await setup(),initial=f.input.baseCommit,path=['binary-add','rename-add'].includes(kind)?'new.txt':'value.txt'
    if(kind==='delete')await unlink(join(f.sourceRepository,path))
    else if(kind==='rename' || kind==='rename-add')await git(f.sourceRepository,'mv','value.txt',kind==='rename-add'?'new.txt':'development.txt')
    else await writeFile(join(f.sourceRepository,path),binary?Buffer.from([0,1,2]):'development\n')
    await git(f.sourceRepository,'add','.');await git(f.sourceRepository,'commit','-m','dev')
    const development=await git(f.sourceRepository,'rev-parse','HEAD')
    await git(f.sourceRepository,'checkout','-b','uat',initial)
    if(kind==='rename')await git(f.sourceRepository,'mv','value.txt','uat.txt')
    else await writeFile(join(f.sourceRepository,path),binary?Buffer.from([0,3,4]):'uat\n')
    await git(f.sourceRepository,'add','.');await git(f.sourceRepository,'commit','-m','uat')
    const targetCommit=await git(f.sourceRepository,'rev-parse','HEAD')
    const adapter=await createManagedWorkspaces({root:f.root,sourceRepository:f.sourceRepository,targetCommit,taskBase:initial})
    await assert.rejects(adapter.prepare({...f.input,baseCommit:development}),/WORKSPACE_CONFLICT_UNSUPPORTED/)
    assert.deepEqual(await readdir(f.root),[])
  }
})

test('双方独立新增同路径UTF8冲突保留原生marker，解决前不得交付且源checkout不变',async()=>{
  const f=await setup(),taskBase=f.input.baseCommit,path='new-calculator.java'
  await writeFile(join(f.sourceRepository,path),'class Calculator { int value = 1; }\n')
  await git(f.sourceRepository,'add','.');await git(f.sourceRepository,'commit','-m','development calculator')
  const development=await git(f.sourceRepository,'rev-parse','HEAD')
  await git(f.sourceRepository,'checkout','-b','uat',taskBase)
  await writeFile(join(f.sourceRepository,path),'class Calculator { int value = 1000; }\n')
  await git(f.sourceRepository,'add','.');await git(f.sourceRepository,'commit','-m','uat calculator')
  const targetCommit=await git(f.sourceRepository,'rev-parse','HEAD'),sourceIndex=await readFile(join(f.sourceRepository,'.git/index'))
  const adapter=await createManagedWorkspaces({root:f.root,sourceRepository:f.sourceRepository,targetCommit,taskBase})
  const prepared=await adapter.prepare({...f.input,baseCommit:development})
  assert.deepEqual(prepared.conflictPaths,[path]);await adapter.execute(prepared)
  const content=await readFile(join(prepared.directory,path),'utf8')
  assert.match(content,/^<<<<<<< /m);assert.match(content,/^=======/m);assert.match(content,/^>>>>>>> /m)
  assert.match(content,/value = 1;/);assert.match(content,/value = 1000;/)
  await assert.rejects(assertWorkspaceConflictsResolved(prepared),/WORKSPACE_CONFLICT_UNRESOLVED/)
  await writeFile(join(prepared.directory,path),'class Calculator { int value = 1; }\n')
  await assertWorkspaceConflictsResolved(prepared)
  assert.equal(await git(f.sourceRepository,'rev-parse','HEAD'),targetCommit)
  assert.deepEqual(await readFile(join(f.sourceRepository,'.git/index')),sourceIndex)
  assert.equal(await readFile(join(f.sourceRepository,path),'utf8'),'class Calculator { int value = 1000; }\n')
})

test('v13只重放可信任务起点之后差异，不把main继承内容带到UAT；缺起点或非祖先拒绝',async()=>{
  const f=await setup(),initial=f.input.baseCommit
  await writeFile(join(f.sourceRepository,'unrelated-main.txt'),'must not ship\n')
  await git(f.sourceRepository,'add','.');await git(f.sourceRepository,'commit','-m','unrelated main history')
  const taskBase=await git(f.sourceRepository,'rev-parse','HEAD')
  await writeFile(join(f.sourceRepository,'value.txt'),'task fix\n')
  await git(f.sourceRepository,'add','.');await git(f.sourceRepository,'commit','-m','task fix')
  await writeFile(join(f.sourceRepository,'later-user.txt'),'keep later branch commit\n')
  await git(f.sourceRepository,'add','.');await git(f.sourceRepository,'commit','-m','user follow-up')
  const development=await git(f.sourceRepository,'rev-parse','HEAD')
  await git(f.sourceRepository,'checkout','-b','uat',initial)
  await writeFile(join(f.sourceRepository,'uat-only.txt'),'keep UAT\n')
  await git(f.sourceRepository,'add','.');await git(f.sourceRepository,'commit','-m','uat')
  const targetCommit=await git(f.sourceRepository,'rev-parse','HEAD')
  await assert.rejects(createManagedWorkspaces({root:f.root,sourceRepository:f.sourceRepository,targetCommit}),/WORKSPACE_TARGET_INVALID/)
  const invalid=await createManagedWorkspaces({root:f.root,sourceRepository:f.sourceRepository,targetCommit,taskBase:targetCommit})
  await assert.rejects(invalid.prepare({...f.input,baseCommit:development}),/TASK_BASE_NOT_ANCESTOR/)
  const adapter=await createManagedWorkspaces({root:f.root,sourceRepository:f.sourceRepository,targetCommit,taskBase})
  const prepared=await adapter.prepare({...f.input,baseCommit:development})
  assert.deepEqual(prepared.conflictPaths,[])
  await adapter.execute(prepared)
  await assert.rejects(readFile(join(prepared.directory,'unrelated-main.txt')),/ENOENT/)
  assert.equal(await readFile(join(prepared.directory,'uat-only.txt'),'utf8'),'keep UAT\n')
  assert.equal(await readFile(join(prepared.directory,'later-user.txt'),'utf8'),'keep later branch commit\n')
  assert.equal(await readFile(join(prepared.directory,'value.txt'),'utf8'),'task fix\n')
  assert.deepEqual((await git(prepared.directory,'diff','--name-only',targetCommit,prepared.mergeTree)).split('\n'),['later-user.txt','value.txt'])
})
