import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('运行看板保留左侧菜单并替换右侧整体内容', async () => {
  const source = await readFile(new URL('../packages/dingtalk-dsh-observer/web-client.js', import.meta.url), 'utf8')
  assert.match(source, /name: 'shell\.overlay'/)
  assert.match(source, /id: 'dingtalk-dsh-observer'/)
  assert.match(source, /name: 'sidebar\.footer\.action'/)
  assert.match(source, /id: 'dingtalk-dsh-observer-entry'/)
  assert.match(source, /钉钉群聊运行看板/)
  assert.match(source, /onClick: \(\) => setOpen\(true\)/)
  assert.match(source, /closest\('\[role="treeitem"\]'\)/)
  assert.match(source, /if \(!isOpen\) return null/)
  assert.match(source, /await openSession\(sessionId, parentSessionId\); setOpen\(false\)/)
  assert.match(source, /getComputedStyle\(element\)\.backgroundColor/)
  assert.match(source, /element\.setAttribute\('aria-selected', 'false'\)/)
  assert.match(source, /name\.endsWith\('_selected'\)/)
  assert.match(source, /restoreSessionSelection\(\)/)
  assert.match(source, /outline: 'none', boxShadow: 'none'/)
  assert.match(source, /height: 52, boxSizing: 'border-box'/)
  assert.match(source, /fontSize: 15, fontWeight: 400[\s\S]*'运行看板'/)
  assert.match(source, /React\.createElement\(StateDot, \{ state: updatedAt \? 'done' : 'ongoing', size: 7 \}\)/)
  assert.match(source, /updatedAt \? '运行正常' : '正在连接'/)
  assert.match(source, /`更新于 \$\{fmtTime\(updatedAt\)\}`/)
  assert.doesNotMatch(source, /`运行态 · \$\{updatedAt/)
  assert.match(source, /height: 38, display: 'flex'/)
  assert.match(source, /borderBottom: activePage === page\.id \? '2px solid #4d6bfe'/)
  assert.match(source, /borderRadius: 999/)
  assert.doesNotMatch(source, /conversation\.view/)
  assert.match(source, /const \[sidebarWidth, setSidebarWidth\] = useState\(280\)/)
  assert.match(source, /new ResizeObserver\(update\)/)
  assert.match(source, /position: 'fixed', top: 0, right: 0, bottom: 0, left: sidebarWidth, zIndex: 900/)
  assert.match(source, /运行看板/)
  assert.match(source, /require\('@deepseek-ai\/dsh-client-ui-primitives'\)/)
  assert.match(source, /React\.createElement\(Button, \{ variant: 'outline', size: 'sm'/)
  assert.match(source, /React\.createElement\(StateDot/)
  assert.match(source, /React\.createElement\(Pill/)
  assert.match(source, /\/state\/groups/)
  assert.match(source, /\/state\/tasks/)
  assert.match(source, /\/state\/activities/)
  assert.match(source, /\/state\/supervisor\/alerts/)
  assert.match(source, /state: 'queued'/)
  assert.match(source, /state: 'running'/)
  assert.match(source, /state: 'waiting'/)
  assert.match(source, /state: 'completed', label: '已完成'/)
  assert.match(source, /task\.state === 'completed'/)
  assert.match(source, /群聊会话/)
  assert.match(source, /任务看板/)
  assert.match(source, /height: 'calc\(100dvh - 238px\)', minHeight: 420, maxHeight: 'calc\(100dvh - 238px\)'/)
  assert.match(source, /minHeight: 'calc\(100dvh - 138px\)'/)
  assert.match(source, /minHeight: 'calc\(100dvh - 90px\)'/)
  assert.doesNotMatch(source, /max\(1000px/)
  assert.match(source, /boxSizing: 'border-box'/)
  assert.match(source, /gridTemplateColumns: 'repeat\(4, minmax\(320px, 1fr\)\)'/)
  assert.match(source, /overflowY: 'scroll'/)
  assert.match(source, /scrollbarGutter: 'stable'/)
  assert.match(source, /activePage === 'tasks' \? 1480 : 1240/)
  assert.match(source, /归档任务/)
  assert.match(source, /id: 'alerts', label: '告警'/)
  assert.match(source, /id: 'tasks', label: '任务看板' \}, \{ id: 'authorizations', label: '授权审批'/)
  assert.match(source, /\/state\/authorizations/)
  assert.match(source, /\/authorizations\/\$\{encodeURIComponent\(requestId\)\}\/decision/)
  assert.match(source, /const authorizationPageSize = 10/)
  assert.match(source, /setSelectedAuthorizationId\(item\.requestId\)/)
  assert.match(source, /aria-label': '授权申请单详情'/)
  assert.match(source, /现场证据 ·/)
  assert.match(source, /selectedAuthorization\.evidence/)
  assert.match(source, /已尝试 ·/)
  assert.match(source, /selectedAuthorization\.attemptedActions/)
  assert.match(source, /finally \{ setNavigatingSessionId\(''\) \}/)
  assert.match(source, /currentAuthorizationPage/)
  assert.match(source, /每页 \$\{authorizationPageSize\} 条/)
  assert.match(source, /React\.createElement\('span', null, '申请摘要'\)/)
  assert.match(source, /当前异常/)
  assert.match(source, /label: `恢复历史 \$\{filteredResolvedAlerts\.length\}`/)
  assert.match(source, /aria-label': '告警状态视图'/)
  assert.match(source, /const resolvedAlertPageSize = 10/)
  assert.match(source, /筛选告警类型/)
  assert.match(source, /id: 'message-channel', label: '消息通道'/)
  assert.match(source, /id: 'leaf-session', label: '叶子会话'/)
  assert.match(source, /id: 'goal', label: '任务目标'/)
  assert.match(source, /setResolvedAlertPage\(1\)/)
  assert.match(source, /群聊消息/)
  assert.match(source, /message\.senderName/)
  assert.match(source, /message\.occurredAt/)
  assert.match(source, /const pageSize = 10/)
  assert.match(source, /选择群聊会话/)
  assert.match(source, /role: 'tablist', 'aria-label': '群聊数据视图'/)
  assert.match(source, /筛选投递状态/)
  assert.match(source, /筛选发件状态/)
  assert.match(source, /Agent 投递/)
  assert.match(source, /agentDeliveryStatus/)
  assert.match(source, /label: `Outbox \$\{selectedOutbox\.length\}`/)
  assert.match(source, /const selectedOutbox/)
  assert.match(source, /const outboxPageSize = 10/)
  assert.match(source, /已回读确认/)
  assert.match(source, /待回读确认/)
  assert.match(source, /message\.readbackRequired === true/)
  assert.match(source, /message\.sourceMessageId/)
  assert.match(source, /message\.replyToMessageId/)
  assert.match(source, /message\.deliveredMessageId/)
  assert.match(source, /message\.outboundId/)
  assert.match(source, /setOutboxPage\(1\)/)
  assert.doesNotMatch(source, /label: 'Resident'/)
  assert.match(source, /ctx\.sessions\.openSubagent/)
  assert.match(source, /ctx\.sessions\.open\(sessionId\)/)
  assert.match(source, /refreshSubagents\(parentSessionId\)/)
  assert.match(source, /正在打开会话…/)
  assert.match(source, /border: `1px solid \$\{colors\.border\}`/)
  assert.match(source, /background: colors\.cardSurface/)
  assert.doesNotMatch(source, /transform: hovered/)
  assert.doesNotMatch(source, /scale\(/)
  assert.match(source, /const statusTag =/)
  assert.match(source, /statusTag\(status\.label, status\.state\)/)
  assert.doesNotMatch(source, /\$\{group\.messages\?\.length \?\? 0\} 条消息/)
  assert.match(source, /const tableFrame =/)
  assert.match(source, /const tableHeadCell =/)
  assert.match(source, /const tableBodyCell =/)
  assert.match(source, /const tableFooter =/)
  assert.match(source, /const toolbar =/)
  assert.match(source, /筛选审批状态/)
  assert.match(source, /style: tableFrame/)
  assert.match(source, /style: tableFooter/)
  assert.match(source, /React\.createElement\(Button, \{ variant: 'outline', size: 'sm'/)
  assert.match(source, /0 8px 20px rgba\(15,23,42,\.08\), 0 2px 6px rgba\(15,23,42,\.05\)/)
  assert.match(source, /padding: '8px 12px 16px 8px'/)
  assert.match(source, /navigator\.clipboard\.writeText/)
  assert.match(source, /document\.execCommand\('copy'\)/)
  assert.match(source, /copyButton\(task\.taskId, ' Task'\)/)
  assert.match(source, /task\.title \|\| task\.objective/)
  assert.doesNotMatch(source, /copyButton\(task\.childSessionId/)
  assert.match(source, /overflowWrap: 'anywhere'/)
  assert.match(source, /WebkitLineClamp: 4/)
  assert.doesNotMatch(source, /task\.childSessionId \|\| '—'/)
  assert.match(source, /copyButton\(selectedGroup\.residentSessionId, '会话 ID'\)/)
  assert.match(source, /\(data\?\.groups \|\| \[\]\)\.length > 1/)
  assert.match(source, /\/tasks\/\$\{encodeURIComponent\(task\.taskId\)\}\/archive/)
  assert.match(source, /task\.state === 'completed' && task\.archivedAt/)
  assert.doesNotMatch(source, /打开常驻对话 \/ 轨迹/)
  assert.doesNotMatch(source, /打开对话 \/ 轨迹/)
  assert.match(source, /inject: \['slots', 'sessions'\]/)
  assert.doesNotMatch(source, /\/config\//)
  assert.match(source, /method: 'POST'/)
})

test('Agent配置页面提供叶子任务并行上限且默认值为5', async () => {
  const source = await readFile(new URL('../packages/dingtalk-dsh-assistant/web-client.js', import.meta.url), 'utf8')
  assert.match(source, /叶子任务并行上限/)
  assert.match(source, /useState\(5\)/)
  assert.match(source, /maxConcurrentTasks/)
  assert.match(source, /min: 1, max: 50/)
})
