import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('运行看板使用DSH原生入口并提供任务交互', async () => {
  const source = await readFile(new URL('../packages/dingtalk-dsh-observer/web-client.js', import.meta.url), 'utf8')
  assert.match(source, /sidebar\.footer\.action/)
  assert.match(source, /shell\.overlay/)
  assert.match(source, /运行看板/)
  assert.match(source, /viewBox: '0 0 24 24'/)
  assert.match(source, /\/state\/groups/)
  assert.match(source, /\/state\/tasks/)
  assert.match(source, /\/state\/activities/)
  assert.match(source, /\/state\/supervisor\/alerts/)
  assert.match(source, /state: 'queued'/)
  assert.match(source, /state: 'running'/)
  assert.match(source, /state: 'waiting'/)
  assert.match(source, /state: 'completed', label: '已完成'/)
  assert.match(source, /task\.state === 'completed'/)
  assert.match(source, /群聊会话/)
  assert.match(source, /任务看板/)
  assert.match(source, /max\(1000px, calc\(100dvh - 120px\)\)/)
  assert.match(source, /boxSizing: 'border-box'/)
  assert.match(source, /gridTemplateColumns: 'repeat\(4, minmax\(320px, 1fr\)\)'/)
  assert.match(source, /overflowY: 'scroll'/)
  assert.match(source, /scrollbarGutter: 'stable'/)
  assert.match(source, /activePage === 'tasks' \? 1480 : 1240/)
  assert.match(source, /归档任务/)
  assert.match(source, /id: 'alerts', label: '告警'/)
  assert.match(source, /id: 'tasks', label: '任务看板' \}, \{ id: 'authorizations', label: '授权审批'/)
  assert.match(source, /\/state\/authorizations/)
  assert.match(source, /\/authorizations\/\$\{encodeURIComponent\(requestId\)\}\/decision/)
  assert.match(source, /const authorizationPageSize = 10/)
  assert.match(source, /setSelectedAuthorizationId\(item\.requestId\)/)
  assert.match(source, /aria-label': '授权申请单详情'/)
  assert.match(source, /现场证据 ·/)
  assert.match(source, /selectedAuthorization\.evidence/)
  assert.match(source, /已尝试 ·/)
  assert.match(source, /selectedAuthorization\.attemptedActions/)
  assert.match(source, /finally \{ setNavigatingSessionId\(''\) \}/)
  assert.match(source, /currentAuthorizationPage/)
  assert.match(source, /每页 \$\{authorizationPageSize\} 条/)
  assert.match(source, /React\.createElement\('span', null, '申请摘要'\)/)
  assert.match(source, /当前异常/)
  assert.match(source, /已恢复历史/)
  assert.match(source, /const resolvedAlertPageSize = 10/)
  assert.match(source, /筛选告警类型/)
  assert.match(source, /id: 'message-channel', label: '消息通道'/)
  assert.match(source, /id: 'leaf-session', label: '叶子会话'/)
  assert.match(source, /id: 'goal', label: '任务目标'/)
  assert.match(source, /setResolvedAlertPage\(1\)/)
  assert.match(source, /群聊消息/)
  assert.match(source, /message\.senderName/)
  assert.match(source, /message\.occurredAt/)
  assert.match(source, /const pageSize = 10/)
  assert.match(source, /选择群聊会话/)
  assert.match(source, /Agent 投递/)
  assert.match(source, /agentDeliveryStatus/)
  assert.doesNotMatch(source, /label: 'Resident'/)
  assert.match(source, /ctx\.sessions\.openSubagent/)
  assert.match(source, /ctx\.sessions\.open\(sessionId\)/)
  assert.match(source, /refreshSubagents\(parentSessionId\)/)
  assert.match(source, /正在打开会话…/)
  assert.match(source, /border: `1px solid \$\{colors\.border\}`/)
  assert.match(source, /background: colors\.cardSurface/)
  assert.doesNotMatch(source, /transform: hovered/)
  assert.doesNotMatch(source, /scale\(/)
  assert.match(source, /justifySelf: 'start', width: 'max-content', whiteSpace: 'nowrap'/)
  assert.doesNotMatch(source, /\$\{group\.messages\?\.length \?\? 0\} 条消息/)
  assert.match(source, /padding: '14px 12px'/)
  assert.match(source, /boxShadow: '0 4px 16px rgba\(15,23,42,\.07\)'/)
  assert.match(source, /minHeight: 44, boxSizing: 'border-box'/)
  assert.match(source, /0 8px 20px rgba\(15,23,42,\.08\), 0 2px 6px rgba\(15,23,42,\.05\)/)
  assert.match(source, /padding: '8px 12px 16px 8px'/)
  assert.match(source, /navigator\.clipboard\.writeText/)
  assert.match(source, /document\.execCommand\('copy'\)/)
  assert.match(source, /copyButton\(task\.taskId, ' Task'\)/)
  assert.doesNotMatch(source, /copyButton\(task\.childSessionId/)
  assert.match(source, /overflowWrap: 'anywhere'/)
  assert.match(source, /WebkitLineClamp: 4/)
  assert.doesNotMatch(source, /task\.childSessionId \|\| '—'/)
  assert.match(source, /copyButton\(group\.residentSessionId, '会话 ID'\)/)
  assert.match(source, /\/tasks\/\$\{encodeURIComponent\(task\.taskId\)\}\/archive/)
  assert.match(source, /task\.state === 'completed' && task\.archivedAt/)
  assert.doesNotMatch(source, /打开常驻对话 \/ 轨迹/)
  assert.doesNotMatch(source, /打开对话 \/ 轨迹/)
  assert.match(source, /inject: \['slots', 'sessions'\]/)
  assert.doesNotMatch(source, /\/config\//)
  assert.match(source, /method: 'POST'/)
})

test('Agent配置页面提供叶子任务并行上限且默认值为5', async () => {
  const source = await readFile(new URL('../packages/dingtalk-dsh-assistant/web-client.js', import.meta.url), 'utf8')
  assert.match(source, /叶子任务并行上限/)
  assert.match(source, /useState\(5\)/)
  assert.match(source, /maxConcurrentTasks/)
  assert.match(source, /min: 1, max: 50/)
})
